name: workflow demo
on: 
  push:
    branches:
      - main
      - dev01
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: install decs
        run: |-
          npm install
      - name: start server
        run: npm run test
      - name: check output
        run: |-
          curl http://localhost:3000
